######################### Kitchen Motion ########################################
- alias: Kitchen Motion
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.kitchen_sensor
    to: 'on'
  condition:
  - condition: state
    entity_id: light.kitchen
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.kitchen_sensor_light
    below: 50
  action:
    - choose:
      - conditions:
        - condition: and
          conditions:
          - condition: sun
            after: sunset
          - condition: time
            before: '21:00:00'
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.kitchen
              brightness: >
                {% if states.light.living_room.state == "on"  %}
                  {{ states.light.living_room.attributes.brightness }}
                {% else %}
                  122
                {% endif %}
      - conditions:
        - condition: time
          after: '21:00:00'
          before: '07:45:00'
        - condition: numeric_state
          entity_id: light.living_room
          value_template: >
            {% if states.light.living_room.state == "on"  %}
              {{ states.light.living_room.attributes.brightness }}
            {% else %}
              0
            {% endif %}
          below: 26
        sequence:
          - service: light.turn_on
            entity_id:
              - light.kitchen_1
            data:
              brightness: 2
      - conditions:
        - condition: time
          after: '21:00:00'
          before: '07:45:00'
        - condition: state
          entity_id: light.living_room
          state: 'on'
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.kitchen
              brightness: >
                {% if states.light.living_room.state == "on"  %}
                  {{ states.light.living_room.attributes.brightness }}
                {% else %}
                  2
                {% endif %}
      - conditions:
        - condition: and
          conditions:
          - condition: sun
            before: sunset
          - condition: time
            after: '7:45:00'
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.kitchen
              brightness: >
                {% if states.light.living_room.state == "on"  %}
                  {{ states.light.living_room.attributes.brightness }}
                {% else %}
                  255
                {% endif %}

- alias: Kitchen No Motion Night
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_sensor
    to: 'off'
    for: "00:01:00"
  condition:
  - condition: numeric_state
    entity_id: light.kitchen
    value_template: >
      {% if states.light.kitchen.state == "on"  %}
        {{ states.light.kitchen.attributes.brightness }}
      {% else %}
        11
      {% endif %}
    below: 33
  - condition: time
    after: '21:00:00'
    before: '07:45:00'
  action:
  - service: light.turn_off
    data:
      entity_id: light.kitchen

- alias: Kitchen No Motion Day
  trigger:
  - platform: state
    entity_id: binary_sensor.kitchen_sensor
    to: 'off'
    for: "00:5:00"
  condition:
  - condition: state
    entity_id: light.kitchen
    state: 'on'
  action:
  - service: light.turn_off
    data:
      entity_id: light.kitchen

- alias: Kitchen Fan Off
  trigger:
  - platform: state
    entity_id: switch.kasa_toggle_switch_2
    to: 'on'
    for: "00:20:00"
  - platform: state
    entity_id: light.kitchen
    to: 'off'
  condition:
  - condition: state
    entity_id: light.kitchen
    state: 'off'
  - condition: state
    entity_id: switch.kasa_toggle_switch_2
    state: 'on'
    for: "00:20:00"
  action:
  - service: switch.turn_off
    entity_id: switch.kasa_toggle_switch_2
