################ Home Max Volume Adjustment ##########################################
- alias: Adjust Home Max Valume with TV
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv_2
  condition:
    - condition: template
      value_template: >
          {{ trigger.from_state and
             trigger.to_state.attributes.volume_level !=
             trigger.from_state.attributes.volume_level }}
    - condition: or 
      conditions:
        - condition: state
          entity_id: media_player.living_room_speaker_2
          state:
          - "off"
          - "paused"
        - condition: state
          entity_id: media_player.living_room_speaker_2
          attribute: "media_title"
          state: "AUX"
  action:
        - service: media_player.volume_set
          data_template: 
            entity_id: 'media_player.living_room_speaker_2'
            volume_level: >-
                {{ state_attr('media_player.living_room_tv_2', 'volume_level') * 5 + 0.30 }}

- alias: Mute Home Max with TV
  trigger:
    - platform: state
      entity_id: media_player.living_room_tv_2
  condition:
    - condition: template
      value_template: >
          {{ trigger.from_state and
             trigger.to_state.attributes.is_volume_muted !=
             trigger.from_state.attributes.is_volume_muted }}
  action:
    - service: media_player.volume_mute
      data_template:
        entity_id: 'media_player.living_room_speaker_2'
        is_volume_muted: >-
                {{ state_attr('media_player.living_room_tv_2', 'is_volume_muted') }}

############################## Turn Off TV If Idle for Too Long ###############################

- alias: Turn Off TV
  trigger:
  - platform: state
    entity_id:
      - media_player.living_room_speaker_2 # Home Max
    attribute: "media_title"
    from: "AUX"
    for:
      minutes: 10
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.living_room_tv_2
        state: "on"
      sequence:
      - service: media_player.turn_off
        entity_id: media_player.living_room_tv_2
  - choose:
    - conditions:
        - condition: state
          entity_id: media_player.living_room_speaker_2
          state:
          - "off"
          - "paused"
      sequence:
      - service: media_player.volume_set
        entity_id: media_player.living_room_speaker_2
        data:
          volume_level: 0.25


######################### Living Room Motion ##################################################
- id: '1618414241000'
  alias: Living Room Motion
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_sensor
    to: 'on'
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: light.living_room
      state: 'off'
    - condition: and
      conditions:
      - condition: state
        entity_id: device_tracker.macbook_pro
        state: 'home'
      - condition: state
        entity_id: sensor.macbook_pro_displays
        state: "2"
      - condition: state
        entity_id: light.couch
        state: "off"
  - condition: state
    entity_id: media_player.living_room_tv_2
    state: 'off'
  action:
    - choose:
      - conditions:
        - condition: and
          conditions:
          - condition: sun
            after: sunset
          - condition: time
            before: '21:00:00'
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.living_room
              brightness: >
                {% if states.light.kitchen.state == "on"  %}
                  {{ states.light.kitchen.attributes.brightness }}
                {% else %}
                  122
                {% endif %}
      - conditions:
        - condition: time
          after: '21:00:00'
          before: '07:45:00'
        - condition: state
          entity_id: light.kitchen
          state: 'off'
        sequence:
          - service: light.turn_on
            entity_id:
              - light.desk_1
            data:
              brightness: 2
      - conditions:
        - condition: time
          after: '21:00:00'
          before: '07:45:00'
        - condition: state
          entity_id: light.kitchen
          state: 'on'
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.living_room
              brightness: >
                {% if states.light.living_room.state == "on"  %}
                  {{ states.light.living_room.attributes.brightness }}
                {% elif states.light.kitchen.state == "on"  %}
                  {{ states.light.kitchen.attributes.brightness }}
                {% else %}
                  2
                {% endif %}
      - conditions:
        - condition: and
          conditions:
          - condition: sun
            before: sunset
          - condition: time
            after: '7:45:00'
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.living_room
              brightness: >
                {% if states.light.living_room.state == "on"  %}
                  {{ states.light.living_room.attributes.brightness }}
                {% elif states('light.kitchen') == "on"  %}
                  {{ state_attr('light.kitchen', 'brightness') }}
                {% else %}
                  255
                {% endif %}

- alias: Living Room No Motion Night
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_sensor
    to: 'off'
    for: "00:01:00"
  - platform: state
    entity_id: media_player.living_room_tv_2
    to: 'off'
  condition:
  - condition: numeric_state
    entity_id: light.living_room
    value_template: >
      {% if states.light.living_room.state == "on"  %}
        {{ states.light.living_room.attributes.brightness }}
      {% else %}
        11
      {% endif %}
    below: 26
  - condition: state
    entity_id: binary_sensor.living_room_sensor
    state: 'off'
    for: "00:01:00"
  - condition: state
    entity_id: media_player.living_room_tv_2
    state: 'off'
  - condition: time
    after: '21:00:00'
    before: '07:45:00'
  action:
  - service: light.turn_off
    data:
      entity_id:
        - light.living_room
        - light.office
  - service: media_player.turn_off
    entity_id: media_player.living_room_tv_2

- alias: Living Room No Motion Day
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_sensor
    to: 'off'
    for: "00:25:00"
  - platform: state
    entity_id: media_player.living_room_tv_2
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.living_room_sensor
    state: 'off'
    for: "00:25:00"
  - condition: state
    entity_id: light.living_room
    state: 'on'
  - condition: state
    entity_id: media_player.living_room_tv_2
    state: 'off'
  action:
    - choose:
      - conditions:
        - condition: state
          entity_id: device_tracker.macbook_pro
          state: 'home'
        - condition: state
          entity_id: sensor.macbook_pro_displays
          state: "2"
        sequence:
          - service: light.turn_off
            entity_id:
              - light.couch
              - light.middle
      default:
        - service: light.turn_off
          data:
            entity_id: light.living_room
